// <auto-generated />
using BookApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BookApi.Migrations
{
    [DbContext(typeof(BookContext))]
    partial class BookContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("BookApi.Models.Book", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd();

                b.Property<string>("Author")
                    .IsRequired()
                    .HasMaxLength(75);

                b.Property<string>("Category")
                    .IsRequired();

                b.Property<string>("Title")
                    .IsRequired();

                b.HasKey("Id");

                b.ToTable("Books");

                b.HasData(
                    new
                    {
                        Id = 1,
                        Author = "John Doe",
                        Category = "Fantasy",
                        Title = "Book one of trilogy"
                    },
                    new
                    {
                        Id = 2,
                        Author = "John Doe",
                        Category = "Fantasy",
                        Title = "Book two of trilogy"
                    },
                    new
                    {
                        Id = 3,
                        Author = "John Doe",
                        Category = "Fantasy",
                        Title = "Book three of trilogy"
                    });
            });
#pragma warning restore 612, 618
        }
    }
}
